*
{
margin:0;
padding:0;
}

body
{
background-color:#333;
white-space:nowrap;
}


.page
{
margin:0 auto;
overflow:hidden;
}

.pageImg
{
position:absolute;
z-index:0;
}

.pageText
{
position:absolute;
z-index:1;
word-spacing:0;
}

.l
{
position:absolute;
}

.w
{
position:relative;
}

.p
{
position:absolute;
}

.t
{
position:relative;
}

$fontfaces; separator="\n"$

$fonts; separator="\n"$

$colors; separator="\n"$